all:
  children:
    webserver:
      hosts:
        ansible1:
          server_role: webserver
          max_connections: 200
          web_port: 80
    database:
      hosts:
        ansible2:
          server_role: database
          max_connections: 500
          db_port: 3306
