---
- name: main lab file
  become: true
  hosts: all
  tasks:
    - name: create facts.d directory
      ansible.builtin.file:
        dest: /etc/ansible/facts.d
        state: directory

    - name: copy content from custom.fact to destination /etc/ansible/facts.d
      ansible.builtin.copy:
        src: files/custom.fact
        dest: /etc/ansible/facts.d/custom.fact

    - name: reload facts
      ansible.builtin.setup:

    - name: print custom fact name
      ansible.builtin.debug:
        msg: "The custom fact name is {{ ansible_local['custom']['app']['name'] }}"

    - name: print version and state of the custom fact
      ansible.builtin.debug:
        msg: "Host {{ ansible_hostname }} is running app version {{ ansible_local['custom']['app']['version'] }} in {{ ansible_local['custom']['app']['state'] }} state"

    - name: print message only on webserver
      ansible.builtin.debug:
        msg: "This is a webserver with {{ max_connections }} max connections"
      when: server_role == "webserver"

    - name: print message only on database
      ansible.builtin.debug:
        msg: "This is a database with {{ max_connections }} max connections"
      when: server_role == "database"

    - name: install packages on all hosts
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      loop:
        - vim-enhanced
        - curl
        - wget

    - name: print message if backup enabled is true
      ansible.builtin.debug:
        msg: "Back up enabled on {{ ansible_hostname }}"
      when: backup_enabled

    - name: check if custom.fact exists
      ansible.builtin.command:
        cmd: ls /etc/ansible/facts.d/custom.fact
      register: fact_check
      ignore_errors: true
      changed_when: fact_check.rc != 0

    - name: print custom.fact file exists
      ansible.builtin.debug:
        msg: "Custom fact file exists on {{ ansible_hostname }}"
      when: fact_check.rc == 0
...
