all:
  children:
    webservers:
      children:
        dev:
          hosts:
            ansible1:
              ansible_host: 192.168.1.81
              env: development
              max_connections: 50
              web_port: 8080
        staging:
          hosts:
            ansible2:
              ansible_host: 192.168.1.82
              env: staging
              max_connections: 100
              web_port: 8080
        prod:
          hosts:
            ansible3:
              ansible_host: 192.168.1.83
              env: production
              max_connections: 500
              web_port: 80
